"""add gifts table

Revision ID: 38567cb18485
Revises: b2c3d4e5f6a7
Create Date: 2026-08-30 00:06:11.164819
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38567cb18485'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wedding_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('received_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('gifts_guest_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], name=op.f('gifts_wedding_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('gifts_pkey'))
    )
    op.create_index(op.f('gifts_guest_id_idx'), 'gifts', ['guest_id'], unique=False)
    op.create_index(op.f('gifts_wedding_id_idx'), 'gifts', ['wedding_id'], unique=False)
    op.drop_index(op.f('bridesmaid_items_guest_id_idx'), table_name='cortage_items')
    op.drop_index(op.f('bridesmaid_items_wedding_id_idx'), table_name='cortage_items')
    op.create_index(op.f('cortage_items_guest_id_idx'), 'cortage_items', ['guest_id'], unique=False)
    op.create_index(op.f('cortage_items_wedding_id_idx'), 'cortage_items', ['wedding_id'], unique=False)
    op.drop_index(op.f('savings_targets_wedding_id_idx'), table_name='savings_targets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('savings_targets_wedding_id_idx'), 'savings_targets', ['wedding_id'], unique=True)
    op.drop_index(op.f('cortage_items_wedding_id_idx'), table_name='cortage_items')
    op.drop_index(op.f('cortage_items_guest_id_idx'), table_name='cortage_items')
    op.create_index(op.f('bridesmaid_items_wedding_id_idx'), 'cortage_items', ['wedding_id'], unique=False)
    op.create_index(op.f('bridesmaid_items_guest_id_idx'), 'cortage_items', ['guest_id'], unique=False)
    op.drop_index(op.f('gifts_wedding_id_idx'), table_name='gifts')
    op.drop_index(op.f('gifts_guest_id_idx'), table_name='gifts')
    op.drop_table('gifts')
    # ### end Alembic commands ###
