"""rename bridesmaid_items to cortage_items + support groomsman

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-08-29
"""

from collections.abc import Sequence

from alembic import op

revision: str = "b2c3d4e5f6a7"
down_revision: str | None = "e7f8a9b0c1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # bridesmaid_items -> cortage_items (generic for bridesmaid + groomsman)
    # Keep constraint name unchanged to avoid extra DDL; table rename preserves PK/FK.
    op.rename_table("bridesmaid_items", "cortage_items")
    # Rename indexes that contain old table name (if any autogenerated with table prefix)
    # SQLAlchemy used op.f("...") so index names are not table-prefixed; only PK/FK remain.
    # Rename the unique constraint explicitly via raw SQL for portability (optional).
    # PostgreSQL: constraint name remains bridesmaid_items_guest_id_key, still valid.
    pass


def downgrade() -> None:
    op.rename_table("cortage_items", "bridesmaid_items")
